# Numpy 

Numpy (or NumPy) is an incredibly fast Linear Algebra Library for Python and it's used by any other Data Science library.

## Installation Instructions

It is highly recommended that you install Python using the Anaconda distribution from the Environment tab in the Anaconda Navigator.

## Using Numpy

Once installed NumPy you can import it as a library:

In [3]:
import numpy as np


# Numpy Arrays

### From a Python List

In [4]:
my_list = [1, 2, 3]
my_list

[1, 2, 3]

In [5]:
np.array(my_list)

array([1, 2, 3])

In [6]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are many other ways to generate Arrays

### arange

Return evenly-spaced values within a given interval.

In [8]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones(3)

array([1., 1., 1.])

In [13]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [14]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [15]:
np.linspace(0, 10, 50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

### eye

Creates an identity matrix

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

### rand
Create an array of the given shape data from a uniform distribution in ``[0, 1)``.

In [17]:
np.random.rand(2)

array([0.36142418, 0.3337723 ])

In [18]:
np.random.rand(5, 5)

array([[0.44331793, 0.74132989, 0.61869025, 0.23389701, 0.93044039],
       [0.03214202, 0.63727379, 0.90292092, 0.20701773, 0.46292102],
       [0.17762503, 0.42786384, 0.33644163, 0.32023486, 0.58649251],
       [0.91708992, 0.99219352, 0.50710684, 0.46091326, 0.28593914],
       [0.55931609, 0.80312598, 0.70020631, 0.78364126, 0.70142297]])

### randn
Create an array of the given shape data from the "standard normal"

In [19]:
np.random.randn(2)

array([-0.65909088,  0.4476652 ])

In [20]:
np.random.randn(5, 5)

array([[-0.09292629,  2.08006322,  1.04895936,  0.2699721 , -0.40897547],
       [ 2.65214171,  0.75351175, -0.53535337, -0.14147868,  1.14375106],
       [-0.26547227, -1.38460249, -0.35079365, -0.2332907 , -1.09250361],
       [-0.07160806,  0.74491854, -1.55084443, -0.10281442, -0.49631293],
       [ 0.45831963, -0.03355836,  0.44819313, -0.54632515,  0.44169754]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [21]:
np.random.randint(1, 100)

11

In [22]:
np.random.randint(1, 100, 10)

array([35, 94, 20, 61, 48, 36, 83, 59, 84, 66])

In [23]:
arr = np.arange(25)
ranarr = np.random.randint(0, 50, 10)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
ranarr

array([32,  9, 10, 42, 26, 11, 40,  4, 20, 12])

## Reshape
Returns an array containing the same data with a new shape.

In [26]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max, min, argmax, argmin

Methods for finding `max` or `min` values or to find their index locations using `argmin` or `argmax`

In [27]:
ranarr

array([32,  9, 10, 42, 26, 11, 40,  4, 20, 12])

In [28]:
ranarr.max()

42

In [29]:
ranarr.argmax()

3

In [30]:
ranarr.min()

4

In [31]:
ranarr.argmin()

7

## Shape

Shape is an attribute that arrays have (not a method):

In [32]:
# Vector
arr.shape

(25,)

In [33]:
# Notice the two sets of brackets
arr.reshape(1, 25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [34]:
arr.reshape(1, 25).shape

(1, 25)

In [35]:
arr.reshape(25, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [36]:
arr.reshape(25, 1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [37]:
arr.dtype

dtype('int64')